authors:
  0xltn0n4m3:
    name: 0xLtn0n4m3        # Author name
    description: el Presidente # Author description
    avatar: urltest         # Author avatar
    slug: url           # Author profile slug
    url: https://ltnoname.dev            # Author website URL